### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by kangarooo** [motatoes/preech#1]
Im looking to find all people who are using voice programms. Is there some forum? Wanted to find your facebook to contact.
Want to find out best universal commands to make for dragon or some other program to code.
Is any way to contact?

**Comment by motatoes** [comment]
Hi, 

I've personally used [CMU sphinx](toolkit) briefly in this project. It was quite easy to embed into the project .. I just had to interface the Java code with Python to use in my Python project. I have no experience working with Dragon API to be honest.

I hope that helps, ..
